import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "@/provider/ChakraProvide";
import { ColorModeScript } from '@chakra-ui/react'
import Navbar from "@/components/Navbar";
import AuthProvider from "@/provider/SessionProvider";
import StoreProvider from "@/redux/StoreProvider";
import theme from "@/provider/theme";
const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <StoreProvider>
        <Providers>
        <ColorModeScript initialColorMode={theme.config.initialColorMode} />
          <Navbar/>
        {children}
        </Providers>
        </StoreProvider>
        </AuthProvider>
        </body>
    </html>
  );
}
